Repository industrustech/hacktoberfestindus2024, pull requests merged in 2023-10, with the labels that each got.

#4 Add files via upload
  t1.css
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#3 Add files via upload
  t1.html
Labels: enhancement, help wanted, HACKTOBERFEST-ACCEPTED

#2 Add files via upload
  ec1.html
Labels: documentation, enhancement, HACKTOBERFEST-ACCEPTED

#1 Add files via upload
  text1.js
Labels: documentation, HACKTOBERFEST-ACCEPTED

#5 Update ec1.html
  ec1.html
Labels: HACKTOBERFEST-ACCEPTED

#8 Update t1.html
  t1.html
Labels: HACKTOBERFEST-ACCEPTED

#9 Create About us.html
  About us.html
Labels: documentation, HACKTOBERFEST-ACCEPTED

#10 Create Contact us.html
  Contact us.html
Labels: help wanted, HACKTOBERFEST-ACCEPTED

#12 Update and rename t1.html to index.html
  index.html
Labels: HACKTOBERFEST-ACCEPTED

#13 Update README.md
  README.md
Labels: documentation, question, HACKTOBERFEST-ACCEPTED
